name: Schedule Publish Posts

on:
  schedule:
    # Schedule to run at 12:01 AM EST (which is 5:01 AM UTC)
    - cron: "1 5 * * *"

jobs:
  update-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Update Post Status
        run: node scripts/updatePosts.js

      - name: Commit and Push if Changed
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add content/blog/*.md
          git diff --staged --quiet || git commit -m "Automatically publish scheduled posts"
          git push
